
<?php

	/* Domain name of the Solr server */
	define('SOLR_SERVER_HOSTNAME', 'localhost');

	/* HTTP Port to connection */
	define('SOLR_SERVER_PORT', '8983');

	/* HTTP Basic Authentication Username */
	define('SOLR_SERVER_USERNAME', '');

	/* HTTP Basic Authentication password */
	define('SOLR_SERVER_PASSWORD', '');

	/* HTTP connection timeout */
	/* This is maximum time in seconds allowed for the http data transfer operation. Default value is 30 seconds */
	define('SOLR_SERVER_TIMEOUT', 500000);
?>
